import "./break block.js"
import "./rightclick.js"
import "./ghost.js"
import "./weakness.js"
import "./night_vision.js"
import "./lightning.js"
import "./soul.js"
import "./wearing_warden_heart.js"
import "./boom.js"
import "./hoe.js"
import "./shovel.js"
import "./soul_bottle.js"